# Generated by Django 4.0.2 on 2022-02-15 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Frage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frage', models.CharField(max_length=200)),
                ('antwort1', models.CharField(max_length=200)),
                ('antwort2', models.CharField(max_length=200)),
                ('antwort3', models.CharField(max_length=200)),
                ('antwort4', models.CharField(max_length=200)),
                ('richtige_antwort', models.CharField(max_length=200)),
                ('schwierigkeitsgrad', models.CharField(choices=[(1, 1), (2, 2), (3, 3)], default=1, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Katalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('katalog_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Teilnehmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('abgeschlossene_fragebogen', models.ManyToManyField(to='Lernplattform.Frage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fragebogen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fragebogen_name', models.CharField(max_length=200)),
                ('fragen', models.ManyToManyField(to='Lernplattform.Frage')),
                ('katalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lernplattform.katalog')),
                ('teilnehmer_liste', models.ManyToManyField(to='Lernplattform.Teilnehmer')),
            ],
        ),
        migrations.AddField(
            model_name='frage',
            name='katalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lernplattform.katalog'),
        ),
    ]
