# Generated by Django 4.0.2 on 2022-02-16 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frage', models.CharField(max_length=200)),
                ('antwort', models.CharField(max_length=200)),
                ('richtige_antwort', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Katalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('katalog_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fragebogen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fragebogen_name', models.CharField(max_length=200)),
                ('fragen', models.ManyToManyField(blank=True, to='fragebogen.Frage')),
                ('katalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fragebogen.katalog')),
            ],
        ),
    ]
