# Generated by Django 4.0.2 on 2022-02-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragebogen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frage',
            name='antwort',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
